### ISSUE TITLE
Help more then a issue.

### ISSUE THREAD

**Issue by steveuk23** [foxriver76/node-bring-api#126]
Hi @foxriver76.
Sorry to ask but this guy has created this [https://github.com/mdhom/node-red-contrib-bring-shopping](url) based on your great api and i've set it up in Node Red and it seems to be working well, however all the items when viewed in my list are in German even though my main Bring list is set as English.
I've tried looking through all the code to see what i could change to help but nothing works.
I have messaged the guy on the other page but he's not replied in months so i was hoping you may have a idea ?
Thanks

**Comment by foxriver76** [comment]
Hi, so I only see `config.locale` being applied.

https://github.com/mdhom/node-red-contrib-bring-shopping/blob/86961ba372f64c20ff69939c548db145d12b24e0/src/bring.js#L218

https://github.com/mdhom/node-red-contrib-bring-shopping/blob/86961ba372f64c20ff69939c548db145d12b24e0/src/bring.js#L243

However, I guess the problem is more, that Bring! API in general works in the Swiss language. Then, the translations need to be applied to retrieve e.g. english item names.

**Comment by steveuk23** [comment]
Yeah I did see that in the code I even tried adding EN in a few places but no luck.
I've no idea how to add a translation so might have to leave it.
Thanks for having a look.

**Comment by foxriver76** [comment]
Actually, the developer could get the correct locale from the config. I have to admit, that it is not that straight forward. 
Example: 
https://github.com/foxriver76/ioBroker.bring/blob/01a8db55c38eab1ba45be6d7a2c7120924d14079/main.js#L134-L147

instead of `EN` try `en-US`

**Comment by steveuk23** [comment]
Thanks I'll try that I don't think the developer is active any more on this which is a shame.
Can I ask in which situation do people use your Bring! Node ? Is it in a Linux distribution.
Sorry I'm new to all this , i do have docker up and running but I don't recognize the install instructions so I'm guessing it's not.
Thanks

**Comment by foxriver76** [comment]
This module here is a wrapper around the API for the programming languages Node.JS/TypeScript. So other developers, which are want to interact with the API can make use of the module, which also provides complete types of the API responses. Hence, the module is not of use for end users directly. This is the case for https://github.com/mdhom/node-red-contrib-bring-shopping and https://github.com/foxriver76/ioBroker.bring (can be used out of the box with ioBroker)

If you are not already using another Smart Home Middleware solution like HASS, you could also give it a try. Else I assume HASS also has some integration for Bring! lists.

**Comment by steveuk23** [comment]
Thanks.
Yeah there is a Hass integration which I did try a few months ago but I couldn't find a way of sending the items of the list to a mobile notification it only seems to allow to add and remove items.
I might have another look.
Thanks for the help.
