### ISSUE TITLE
getItemsDetails Node-Input parameter unclear

### ISSUE THREAD

**Issue by DarrolMusambani** [foxriver76/node-bring-api#6]
Hello,
I'm having trouble getting the getItemsDetails-Node to work if try to push a listUuid into it. So far i tried packing it into 

- msg.payload
- msg.listUuid
- msg.payload.listUuid

it always results in a `Error: Cannot get items for list : 405 - "" `  message, which i find interessting since it appears to be the error message of the regular getItems-Method.
However manually entering a static uuid into the node works just fine.

https://github.com/foxriver76/node-bring-api/blob/4b8237342f37cf763f9179a6f881f1fa19bb7de0/lib/bring.js#L77

**Comment by foxriver76** [comment]
Hi,

I guess you are using Node-RED and probably the https://github.com/mdhom/node-red-contrib-bring-shopping package. Unfortunately, I am not familiar via Node-RED. From the point of my library, `getItemsDetails` expects a list uuid in the same form as `getItems`. I personally not use the `getItemsDetails` method in productive code, maybe @mdhom who thankfully added the method and is the maintainer of https://github.com/mdhom/node-red-contrib-bring-shopping can help you out.

best regards 

fox
